server:
  port: 8080

sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: '{mysql-password}'
  redis:
    host: localhost
    port: 6379
    password: '{redis-password}'
    database: 1
  oss:
    upload-path: /var/project_asset/sky-take-out/uploads/images
  wechat:
    appid: '{appid}'
    secret: '{wechat-secret}'
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:
  shop:
    delivery-fee: 5.21
    shop-address: 江西南昌
    phone: '{phone}'
    shop-name: 苍穹食堂
    shop-id: 1
    description: 10年老店,苍穹食堂为顾客打造专业的大众化美食外送餐饮
  baidu:
    ak: your-ak